import { Department, User, Role } from '../models/employee.model';

export const EMPLOYEE_DATA: User[] = [
  {
    id: 1,
    name: 'yash',
    email: 'yashgoyal322023@gmail.com',
    position: 'Admin',
    department: Department.ENGINEERING,
    salary: 30000,
    role: Role.Admin,
    password: 'Admin@123',
  },
  {
    id: 2,
    name: 'manvendra',
    email: 'manvendragoyal32023@gmail.com',
    position: 'Intern',
    department: Department.INTERN,
    salary: 30000,
    role: Role.Employee,
    password: 'emp2@123',
  },
  {
    id: 3,
    name: 'tanisha',
    email: 'tanishagoyal32023@gmail.com',
    position: 'Intern',
    department: Department.INTERN,
    salary: 30000,
    role: Role.Employee,
    password: 'emp2@123',
  },
  {
    id: 4,
    name: 'jaid',
    email: 'jaid32023@gmail.com',
    position: 'software engineer 2',
    department: Department.ENGINEERING,
    salary: 30000,
    role: Role.Employee,
    password: 'emp4@123',
  },

  {
    id: 5,
    name: 'krishna',
    email: 'krishna32023@gmail.com',
    position: 'software engineer 1',
    department: Department.SALES,
    salary: 30000,
    role: Role.Employee,
    password: 'emp5@123',
  },

  {
    id: 6,
    name: 'krishna',
    email: 'krishna32023@gmail.com',
    position: 'software engineer 1',
    department: Department.HR,
    salary: 30000,
    role: Role.Employee,
    password: 'emp6@123',
  },

  {
    id: 7,
    name: 'krishna',
    email: 'krishna32023@gmail.com',
    position: 'software engineer 1',
    department: Department.FINANCE,
    salary: 300000,
    role: Role.Employee,
    password: 'emp7@123',
  },
  {
    id: 8,
    name: 'krishna goyal',
    email: 'krishna32023@gmail.com',
    position: 'software engineer 1',
    department: Department.FINANCE,
    salary: 300000,
    role: Role.Employee,
    password: 'emp8@123',
  },
  {
    id: 9,
    name: 'saloni',
    email: 'saloni32023@gmail.com',
    position: 'executive',
    department: Department.SALES,
    salary: 30000,
    role: Role.Employee,
    password: 'emp9@123',
  },
];
